// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYENV-2oGMBZNaIH7SukgO9AomevL_mOY',
    appId: '1:139171267033:android:35c5a7d70ce24539af19c8',
    messagingSenderId: '139171267033',
    projectId: 'lenscart-mobile-app',
    authDomain: 'lenscart-mobile-app.firebaseapp.com',
    storageBucket: 'lenscart-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYENV-2oGMBZNaIH7SukgO9AomevL_mOY',
    appId: '1:139171267033:android:35c5a7d70ce24539af19c8',
    messagingSenderId: '139171267033',
    projectId: 'lenscart-mobile-app',
    storageBucket: 'lenscart-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYENV-2oGMBZNaIH7SukgO9AomevL_mOY',
    appId: '1:139171267033:android:35c5a7d70ce24539af19c8',
    messagingSenderId: '139171267033',
    projectId: 'lenscart-mobile-app',
    storageBucket: 'lenscart-mobile-app.firebasestorage.app',
    iosBundleId: 'com.lenscart.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYENV-2oGMBZNaIH7SukgO9AomevL_mOY',
    appId: '1:139171267033:android:35c5a7d70ce24539af19c8',
    messagingSenderId: '139171267033',
    projectId: 'lenscart-mobile-app',
    storageBucket: 'lenscart-mobile-app.firebasestorage.app',
    iosBundleId: 'com.lenscart.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYENV-2oGMBZNaIH7SukgO9AomevL_mOY',
    appId: '1:139171267033:android:35c5a7d70ce24539af19c8',
    messagingSenderId: '139171267033',
    projectId: 'lenscart-mobile-app',
    authDomain: 'lenscart-mobile-app.firebaseapp.com',
    storageBucket: 'lenscart-mobile-app.firebasestorage.app',
  );
}
